[phases.setup]
apt_pkgs = ["libpq-dev"]

[phases.build]
commands = ["pip install -r requirements.txt"]

[phases.start]
commands = [
  "python manage.py migrate",
  "python manage.py collectstatic --noinput",
  "gunicorn erp_services.wsgi:application --bind 0.0.0.0:8000"
]
