volumes:
  redis_data:
  rabbitmq_data:
  postgres_data:

networks:
  app_net:

services:
  api:
    container_name: rest_api
    build:
      context: .
      dockerfile: Dockerfile
    env_file:
      - .env
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    depends_on:
      - redis
      - rabbitmq
      - postgres
    networks:
      - app_net

  celery:
    container_name: celery_worker
    build:
      context: .
      dockerfile: Dockerfile
    env_file:
      - .env
    command: celery -A erp_services worker --loglevel=info
    volumes:
      - .:/app
    networks:
      - app_net
    
  redis:
    container_name: redis_broker
    image: redis:7
    env_file:
      - .env
    volumes:
      - redis_data:/data
    ports:
      - "6379:6379"
    networks:
      - app_net

  rabbitmq:
    image: rabbitmq:3-management
    container_name: rabbitmq_broker
    ports:
      - "5672:5672"
      - "15672:15672"
    env_file:
      - .env
    volumes:
      - rabbitmq_data:/var/lib/rabbitmq
    networks:
      - app_net

  postgres:
    image: postgres:15
    container_name: postgres_db
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    env_file:
      - .env
    ports:
      - "5432:5432"
    networks:
      - app_net
    