# Generated by Django 5.1.7 on 2025-06-13 16:31

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='OneTimeCode',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_used', models.BooleanField(default=False, verbose_name='Usado')),
                ('code', models.BinaryField(verbose_name='Código')),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='account_otp_codes', to=settings.AUTH_USER_MODEL, verbose_name='ID do Usário')),
            ],
            options={
                'verbose_name': 'Código de Tempo Único',
                'verbose_name_plural': 'Códigos de Tempos Únicos',
            },
        ),
    ]
