# Generated by Django 5.1.7 on 2025-06-13 16:36

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jwt_auth', '0002_alter_onetimecode_id'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='onetimecode',
            constraint=models.UniqueConstraint(fields=('account', 'code'), name='unique_account_code'),
        ),
    ]
