# Generated by Django 5.1.7 on 2025-05-14 15:12

import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('first_name', models.CharField(max_length=80, verbose_name='Nome')),
                ('last_name', models.CharField(max_length=80, verbose_name='Sobrenome')),
                ('job_title', models.CharField(default='', max_length=150, verbose_name='Cargo')),
                ('hierarchy_level', models.CharField(choices=[('Aprendiz', 'Apprentice'), ('Estagiário', 'Intern'), ('Colaborador', 'Collaborator'), ('Cordenador', 'Coordinator'), ('Gerente', 'Manager'), ('Diretor', 'Director')], default='', max_length=20, verbose_name='Nível hierárquico')),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='Email')),
                ('otp_secret', models.BinaryField(blank=True, null=True)),
                ('encrypted_cpf', models.BinaryField(blank=True, null=True, unique=True, verbose_name='CPF Criptografado')),
                ('hashed_cpf', models.CharField(blank=True, max_length=64, null=True, unique=True, verbose_name='Hash do CPF')),
                ('phone_number', models.CharField(default='', max_length=20, unique=True, verbose_name='Contato')),
                ('phone_number_region', models.CharField(default='BR', max_length=2, verbose_name='Região')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'Usuário',
                'verbose_name_plural': 'Usuários',
            },
        ),
    ]
