# Generated by Django 5.1.7 on 2025-05-26 18:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='is_authenticated',
            field=models.BooleanField(default=False, verbose_name='Autenticado'),
        ),
    ]
