# Generated by Django 5.1.7 on 2025-05-29 13:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_account_is_authenticated'),
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='account',
            constraint=models.UniqueConstraint(fields=('first_name', 'last_name', 'email', 'phone_number', 'hashed_cpf'), name='Unique User', violation_error_message='Não é possivel adicionar esse usuário'),
        ),
    ]
