# Generated by Django 5.1.7 on 2025-04-08 13:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_alter_account_last_name_alter_account_phone_number'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='account',
            name='cpf',
        ),
        migrations.AddField(
            model_name='account',
            name='cpf_encrypted',
            field=models.BinaryField(blank=True, null=True, unique=True, verbose_name='CPF Criptografado'),
        ),
    ]
