# Generated by Django 5.1.7 on 2025-05-29 13:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_account_unique_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='encrypted_cpf',
            field=models.BinaryField(blank=True, null=True, verbose_name='CPF Criptografado'),
        ),
        migrations.AlterField(
            model_name='account',
            name='hashed_cpf',
            field=models.CharField(blank=True, max_length=64, null=True, verbose_name='Hash do CPF'),
        ),
        migrations.AlterField(
            model_name='account',
            name='phone_number',
            field=models.CharField(default='', max_length=20, verbose_name='Contato'),
        ),
    ]
