# Generated by Django 5.1.7 on 2025-04-10 12:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_remove_account_cpf_account_cpf_encrypted'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='cpf_hash',
            field=models.CharField(blank=True, max_length=64, null=True, unique=True, verbose_name='Hash do CPF'),
        ),
    ]
