# Generated by Django 5.1.7 on 2025-04-11 16:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_account_cpf_hash'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='phone_number_region',
            field=models.CharField(default='BR', max_length=2, verbose_name='Região'),
            preserve_default=False,
        ),
    ]
