# Generated by Django 5.1.7 on 2025-05-29 13:54

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_alter_account_encrypted_cpf_alter_account_hashed_cpf_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='email',
            field=models.EmailField(max_length=254, verbose_name='Email'),
        ),
        migrations.AlterField(
            model_name='account',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True, verbose_name='ID do Usuário'),
        ),
        migrations.AlterField(
            model_name='account',
            name='is_authenticated',
            field=models.BooleanField(default=False, verbose_name='Usuário autenticado'),
        ),
        migrations.AlterField(
            model_name='account',
            name='otp_secret',
            field=models.BinaryField(blank=True, null=True, verbose_name='Segredo OTP'),
        ),
    ]
