# Generated by Django 5.1.7 on 2025-04-11 16:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_account_phone_number_region'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='phone_number_region',
            field=models.CharField(default='BR', max_length=2, verbose_name='Região'),
        ),
    ]
