# Generated by Django 5.1.7 on 2025-04-11 17:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_alter_account_phone_number_region'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='phone_number',
            field=models.CharField(default='', max_length=20, unique=True, verbose_name='Contato'),
        ),
    ]
