# Generated by Django 5.1.7 on 2025-04-25 18:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_alter_account_phone_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='is_2fa_validated',
            field=models.BooleanField(default=False, verbose_name='Autentificação de dois fatores'),
        ),
    ]
