# Generated by Django 5.1.7 on 2025-04-25 19:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_remove_account_is_2fa_validated'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='otp_secret',
            field=models.CharField(blank=True, max_length=32, null=True),
        ),
    ]
