# Generated by Django 5.1.7 on 2025-04-28 10:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0010_account_otp_secret'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='is_2fa_enabled',
            field=models.BooleanField(default=False),
        ),
    ]
