# Generated by Django 5.1.7 on 2025-05-06 19:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0011_account_is_2fa_enabled'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='account',
            name='is_2fa_enabled',
        ),
    ]
