# Generated by Django 5.1.7 on 2025-05-06 19:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0012_remove_account_is_2fa_enabled'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='otp_secret',
            field=models.BinaryField(blank=True, null=True),
        ),
    ]
