# Generated by Django 5.1.7 on 2025-05-08 12:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0013_alter_account_otp_secret'),
    ]

    operations = [
        migrations.RenameField(
            model_name='account',
            old_name='cpf_encrypted',
            new_name='encrypted_cpf',
        ),
        migrations.RenameField(
            model_name='account',
            old_name='cpf_hash',
            new_name='hashed_cpf',
        ),
    ]
