# Generated by Django 5.1.7 on 2025-04-29 17:15

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoice', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameField(
            model_name='card',
            old_name='user',
            new_name='account',
        ),
        migrations.RenameField(
            model_name='card',
            old_name='card_name',
            new_name='name',
        ),
        migrations.CreateModel(
            name='Invoice',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True, verbose_name='ID Fatura')),
                ('name', models.CharField(blank=True, default='', max_length=50, null=True, verbose_name='Nome no cartão')),
                ('purchase_date', models.DateTimeField(verbose_name='Data de compra')),
                ('description', models.TextField(blank=True, default='', null=True, verbose_name='Descrição')),
                ('value', models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='Valor')),
                ('installment', models.IntegerField(default=1, verbose_name='Parcela')),
                ('installments', models.IntegerField(default=1, verbose_name='Parcelas')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='invoices', to=settings.AUTH_USER_MODEL)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='created_invoices', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Fatura',
                'verbose_name_plural': 'Faturas',
                'indexes': [models.Index(fields=['account'], name='invoice_inv_account_2a56d1_idx'), models.Index(fields=['created_at'], name='invoice_inv_created_e51ef2_idx'), models.Index(fields=['purchase_date'], name='invoice_inv_purchas_da4ac2_idx')],
            },
        ),
    ]
