# Generated by Django 5.1.7 on 2025-05-19 13:03

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoice', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='bank',
            field=models.CharField(choices=[('Itaú', 'Itau'), ('Banco do Brasil', 'Banco Do Brasil')], default=django.utils.timezone.now, verbose_name='Banco'),
            preserve_default=False,
        ),
    ]
