# Generated by Django 5.1.7 on 2025-04-29 19:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('invoice', '0002_rename_user_card_account_rename_card_name_card_name_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='invoice',
            old_name='name',
            new_name='card',
        ),
    ]
