# Generated by Django 5.1.7 on 2025-05-19 18:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoice', '0002_invoice_bank'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='purchase',
            name='unique_card_purchase_date_description_installment',
        ),
        migrations.AlterField(
            model_name='purchase',
            name='purchase_date',
            field=models.DateTimeField(verbose_name='Data da compra'),
        ),
        migrations.AddConstraint(
            model_name='invoice',
            constraint=models.UniqueConstraint(fields=('bank', 'invoice_date'), name='unique_bank_invoice_date'),
        ),
    ]
