# Generated by Django 5.1.7 on 2025-05-19 18:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoice', '0003_remove_purchase_unique_card_purchase_date_description_installment_and_more'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='purchase',
            constraint=models.UniqueConstraint(fields=('card', 'purchase_date', 'description', 'installment'), name='unique_card_purchase_date_description_installment'),
        ),
    ]
