# Generated by Django 5.1.7 on 2025-05-19 18:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('invoice', '0004_purchase_unique_card_purchase_date_description_installment'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='purchase',
            name='unique_card_purchase_date_description_installment',
        ),
    ]
