# Generated by Django 5.1.7 on 2025-05-19 18:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoice', '0005_remove_purchase_unique_card_purchase_date_description_installment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='purchase',
            name='purchase_date',
            field=models.DateField(verbose_name='Data da compra'),
        ),
    ]
