# Generated by Django 5.1.7 on 2025-05-21 17:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoice', '0006_alter_purchase_purchase_date'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='purchase',
            constraint=models.UniqueConstraint(fields=('card', 'invoice', 'purchase_date', 'description', 'value', 'installment'), name='unique_purchase'),
        ),
    ]
