# Generated by Django 5.1.7 on 2025-05-21 17:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoice', '0008_remove_purchase_unique_purchase_and_more'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='purchase',
            name='unique_purchase',
        ),
        migrations.AddConstraint(
            model_name='purchase',
            constraint=models.UniqueConstraint(fields=('card', 'invoice', 'purchase_date', 'description', 'value', 'installment', 'installments'), name='unique_purchase', violation_error_message='Já há uma compra com os dados informados'),
        ),
    ]
