# Generated by Django 5.1.7 on 2025-05-21 18:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoice', '0009_remove_purchase_unique_purchase_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='card',
            name='name',
            field=models.CharField(default='', max_length=50, verbose_name='Nome no cartão'),
        ),
    ]
