# Generated by Django 5.1.7 on 2025-05-21 22:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('invoice', '0010_alter_card_name'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='purchase',
            name='unique_purchase',
        ),
    ]
